VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "LiabOutput"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public ClassName As String
Public TotInt As Double
Public TotPrin As Double
Public TotCash As Double
Public InPrice As Double
Public InSpread As Double
Public CalcYield As Double
Public CalcSpread As Double
Public CalcPrice As Double
Public WAL As Double
Public MacDur As Double
Public ModDur As Double

